version: '3.9'
services:
  python:
    container_name: python
    image: python:3.10

  requirements:
    image: python:3.10
    volumes:
      - pip3:/usr/local/lib/python3.10/site-packages
      - .:/project
    working_dir: 
      /project
    command: pip3 install -r requirements.txt
  
volumes:
  pip3:
    external: true